Add templates
DawMas/25.6-szablony-html pull request #1
Opened 2019-08-27 19:08 UTC by DawMas

Utwórz teraz nowy katalog projektowy, a w nim katalog /views. Z wiedzą nabytą dotychczas, stwórz teraz samodzielnie widok aplikacji do logowania się przez Google (<a href="/auth/google">). Na pierwszej stronie powinien być opis aplikacji oraz przycisk do logowania, natomiast to, co chcesz zobaczyć po zalogowaniu zależy już tylko od Ciebie :) Oczywiście ma to być tylko 'udawane' logowanie - stwórz po prostu logowania, który będzie przenosił użytkownika na inny widok :) W następnych submodułach zajmiemy się prawdziwym logowaniem przez Google. Powodzenia!

Jak zawsze, po wykonaniu zadań umieść swój kod na Githubie i przekaż link do niego swojemu mentorowi :)

2019-08-28 03:59 UTC, lukaszewczak requested changes

2019-08-28 03:59 UTC, lukaszewczak commented on style.css
> +    margin: 0 auto;
Popraw proszę formatowanie

2019-08-28 03:59 UTC, lukaszewczak commented on views/first-template.pug
> +doctype html
W kodzie nie używasz tego widoku, usuń go proszę.

2019-08-28 03:59 UTC, lukaszewczak commented on views/log.pug
> +        link(rel='stylesheet' type="text/css" href='../style.css')
Przy odwołaniu do pliku `styles.css` nie podajemy tak ścieżki, wystarczy napisać `style.css` i dodać obsługę plików statycznych do serwera **express.js** o której była mowa w module `25.4. Serwowanie plików statycznych`

2019-08-29 16:47 UTC, DawMas commented on views/log.pug
> +        link(rel='stylesheet' type="text/css" href='../style.css')
poprawione ;)

2019-09-01 18:55 UTC, lukaszewczak requested changes

2019-09-01 18:55 UTC, lukaszewczak commented on assets/style.css
> +    width: 100%;
A co to tak wysunięte ;-)? Formatowanie do poprawy

2019-09-02 19:10 UTC, lukaszewczak approved these changes

2019-09-10 19:11 UTC, merged